name: 🔄 Reverse GitHub History (Interactive)

on:
  workflow_dispatch:
    inputs:
      github_username:
        description: "Enter GitHub Username"
        required: true

jobs:
  reverse_history:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Reverse Commit History Script
        env:
          GITHUB_USERNAME: ${{ github.event.inputs.github_username }}
        run: python scripts/reverse_history.py

      - name: Commit & Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add reverse_history_*.md
          git commit -m "🔄 Reversed GitHub History for ${{ github.event.inputs.github_username }}"
          git push
